name: Download webMethods.io Assets

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  download-assets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Use PAT instead of default GITHUB_TOKEN
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      
      - name: Create assets JSON file
        run: |
          cat > assets.json << 'EOL'
          {
            "assets": [
              {
                "name": "FlowService1",
                "type": "flow",
                "description": "Example flow service",
                "version": "1.0",
                "downloadLink": "${{ vars.WEBMETHODS_ASSET_URL1 }}"
              },
              {
                "name": "FlowService2",
                "type": "flow",
                "description": "Another flow service",
                "version": "1.1",
                "downloadLink": "${{ vars.WEBMETHODS_ASSET_URL2 }}"
              }
            ]
          }
          EOL
      
      - name: Download webMethods.io assets
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          TARGET_REPO: "vikash-sharma-0058WT744/TenantCICDRepo"
        run: |
          python download_webmethods_assets.py \
            --json-file assets.json \
            --output-dir ./downloaded_assets \
            --git-repo . \
            --target-repo "$TARGET_REPO"

# Made with Bob
